### ISSUE TITLE
ValueError: Could not find the input entity for PeerUser(user_id=<MY_USER_ID>) (PeerUser)

### ISSUE THREAD

**Issue by 42Craft** [jsavargas/telethon_downloader#65]
I am having trouble keeping this app up and running while using Docker. It seems that the user_id value I assign to the environment variable `TG_AUTHORIZED_USER_ID` cannot be found. Whenever I run the app with this value, I see the following error:
`ValueError: Could not find the input entity for PeerUser(user_id=<MY_USER_ID>) (PeerUser)`

I am successfully able to run the app when I use, for example, the group_id. I have validated my user_id by various means to ensure it exists. I also tried to run the app using my username, but none of these attempts have worked.

Does anyone have any recommendations on how to proceed from here?

**Comment by jsavargas** [comment]
Sorry for the late, were you able to resolve this issue?
 This is the first time I've seen this problem, what tag are you using or are you using docker or direct?

**Comment by Yusseiin** [comment]
Hi, sorry for bad eng. 
I have got the same problem and i have fixed it.
I am on Unraid App.
Seems the problem occured if the chat with the bot is not inizialized before starting the app.
You just need to press "start" in telegram in the bot chat and restart the app.

**Comment by 42Craft** [comment]
> Hi, sorry for bad eng. I have got the same problem and i have fixed it. I am on Unraid App. Seems the problem occured if the chat with the bot is not inizialized before starting the app. You just need to press "start" in telegram in the bot chat and restart the app.

Your reply gave me the motivation to try my configuration again. 

Initially, it was still not working. Then I noticed it did work in my chat with the bot, but not in the group chat. I used the tips from this thread to retrieve the group chat id: https://stackoverflow.com/questions/32423837/telegram-bot-how-to-get-a-group-chat-id

I think it was a combination of using the wrong (group) chat id and not initializing the bot.

Also, I disabled the Telegram bot `privacy mode`, but I am not sure if this is needed to make it work.

Thank you for your reply!

**Comment by Yusseiin** [comment]
> > Hi, sorry for bad eng. I have got the same problem and i have fixed it. I am on Unraid App. Seems the problem occured if the chat with the bot is not inizialized before starting the app. You just need to press "start" in telegram in the bot chat and restart the app.
> 
> Your reply gave me the motivation to try my configuration again. 
> 
> Initially, it was still not working. Then I noticed it did work in my chat with the bot, but not in the group chat. I used the tips from this thread to retrieve the group chat id: https://stackoverflow.com/questions/32423837/telegram-bot-how-to-get-a-group-chat-id
> 
> I think it was a combination of using the wrong (group) chat id and not initializing the bot.
> 
> Also, I disabled the Telegram bot `privacy mode`, but I am not sure if this is needed to make it work. Did you adjust the privacy  mode setting of your bot @Yusseiin ?
> 
> Thank you for your reply! 😊

I am not using it in a group, but in a direct chat so I cannot help with that 
My bot has Privacy Mode ENABLED. The privacy mode is useful if you wanna get all the message that are sent in a group, but it can still receive message in a group if you mention the bot in the message with the @nameofthebot

**Comment by 42Craft** [comment]
Thanks.

Closing this because issue has been solved.
